#Sample .travis.yml for R projects

language: r
r:
  - release
  - devel
r_packages:
  - devtools
  - covr
package: cache
bioc_required: true
r_build_args: "--no-manual --no-resave-data"
r_check_args: "--no-manual --timings"
-os:
  - linux
  - osx
before_install:
  Rscript -e 'update.packages(ask = FALSE)'
sudo: required
after_success:
    - Rscript -e 'library(covr); codecov()'
