# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' eigen_cpm
#'
#' Calculates counts per million (cpm) using a gene expression counts matrix
#' as input.
#'
#' @name eigen_cpm
#' @rdname eigen_cpm
#' @keywords internal
#' @aliases eigen_cpm
#' @param counts matrix; a numeric matrix of counts.
#' @return A matrix of cpm values.
#' @author Jason T. Serviss
#' @export
eigen_cpm <- function(counts) {
    .Call('_RNAseqFunctions_eigen_cpm', PACKAGE = 'RNAseqFunctions', counts)
}

#' eigen_log2cpm
#'
#' Calculates log2 counts per million (cpm) using a gene expression counts
#' matrix as input.
#'
#' @name eigen_log2cpm
#' @rdname eigen_log2cpm
#' @keywords internal
#' @aliases eigen_log2cpm
#' @param counts matrix; a numeric matrix of counts.
#' @return A matrix of log2(cpm + 1) values.
#' @author Jason T. Serviss
#' @export
eigen_log2cpm <- function(counts) {
    .Call('_RNAseqFunctions_eigen_log2cpm', PACKAGE = 'RNAseqFunctions', counts)
}

